// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.LykkeService.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ExchangeSettingsResponse
    {
        /// <summary>
        /// Initializes a new instance of the ExchangeSettingsResponse class.
        /// </summary>
        public ExchangeSettingsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExchangeSettingsResponse class.
        /// </summary>
        public ExchangeSettingsResponse(string baseAssetIos = default(string), string baseAssetOther = default(string), bool? signOrder = default(bool?))
        {
            BaseAssetIos = baseAssetIos;
            BaseAssetOther = baseAssetOther;
            SignOrder = signOrder;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseAssetIos")]
        public string BaseAssetIos { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseAssetOther")]
        public string BaseAssetOther { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SignOrder")]
        public bool? SignOrder { get; private set; }

    }
}
